/*
 * Nexus Daily Summary — data source of truth.
 */
window.NEXUS_DATA = {
  launchDate: '2026-07-20',
  launchLabel: '7/20',
  date: '2026-06-25',

  teams: [
    {
      name: 'Inventory Planning',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-700',
      updatedAt: '2026-06-25T18:00:00',
      bullets: [
        'All three green milestones on target — SKU View/Table, SKU Table UI (with mock API), and back-end contracts progressing',
        'Evan: PR #137 open adding sort, filter, search, column visibility, and pagination to the SKU table',
        'Stephen: PR open adding "qty on order" to the inventory SKU report',
        'Rex: LeafLogix PR #19269 open for SKU table endpoint awaiting review',
        'Ned onboarding; Roey on vacation (returns July 6 — BE refinement starts then); Mike rotated off',
        'Open question: Connect is switching from last-30-days to last-4-weeks (L4W) look-back — how much refactoring does that require on the Nexus side?',
        'Watch: Evan blocked — Snowflake RSA key not registered in OPIJWHE-DEV; needs Snowflake admin to resolve',
        'Watch: data contract in Rex\'s WIP SKU table PR needs team review before merging',
        'Watch: Data DRI ownership has shifted and needs formal clarification',
        'Watch: New Purchase Order system (Whit Perkins) — Nexus ops that populate POs require Inventory UI to close the loop',
        'Mitigation: contracts + expected data state agreed to continue work despite blocker; focused discussion scheduled',
        'Blocked: Snowflake → S3 → SQL Server pipeline not yet done — blocking final delivery. Cross-team concern escalated to Eric Livergood, Chris Ostrowski, and Tom Wonneberger',
      ],
    },
    {
      name: 'Dex',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-707',
      updatedAt: '2026-06-25T18:00:00',
      bullets: [
        'Chris shipped the latest Dex build — product management basics live at staging URL',
        'Demo plan set for tomorrow: Gordy leads discussion on the 5 workflows, Chris provides commentary and shows Dex progress',
        'Katie Goodwin: brainstorming Day 2+ use cases with Bilda + Contexta; mapping triggers, invocation type, context, and access needs into a consumable doc',
        'Driban out ~2 weeks on paternity leave; dropped 2 draft PRs before departing — scope held for return',
        'ADR-0005 proposed: capabilities auto-expose to Dex via client-side registry — needs Nexus FE + Dex/agent owner review and sign-off',
        'Product decisions: Phase 1 invocation two existing pathways only (inline deferred to P2); free text as build signal; auditing lean toward "done by Dex" flag + person in conversation',
        'Watch: Gordy proposing Day 1 scope swap — product copy across LSPs out, End-of-Day Reconciliation and Closing Reports in (based on C3 customer interviews). Leadership input needed.',
        'Watch: Scott\'s bandwidth reduced while on AI Budtender; Chris is primary Dex driver — flagged as a potential risk',
        'Watch: no performed-by field in the current audit flow — audit UX clunky; Chris investigating',
      ],
    },
    {
      name: 'Command Center',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-703',
      updatedAt: '2026-06-23T16:48:00',
      paused: true,
      pausedReason: 'On hold — roll-up sections resume with Reporting; two standalone sections (Today\'s Pulse + one Morning Brief item) need separate planning.',
      bullets: [
        'DRI recommendation: piggyback roll-up sections off Reporting work; plan Today\'s Pulse and one Morning Brief item separately as standalone sections',
        'Gordy auditing Command Center to identify all non-roll-up sections and produce a list for planning',
        'Today\'s Pulse and one Morning Brief item confirmed as standalone — not covered by Reporting work; require separate work to determine data sources',
        'Resource shuffle: Mike Luon → Reports; Steven Morton → Inventory Insights; Rex → Inventory Planning (back-end)',
        'Scott on Register Copilot',
        'No channel activity today — milestone canvas for week of 6/22 still not filled in',
      ],
    },
    {
      name: 'Reporting',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      updatedAt: '2026-06-25T18:00:00',
      bullets: [
        'Budtender performance detail page PR merged — on track for tomorrow\'s show-and-tell end-to-end demo',
        'Real data confirmed back in FE by ~3:48 PM; DB restore by Michael tonight with Fivetran resync after',
        'Mack: Loom of current data display shared; mock data fallback (?mock=1) set up for the demo',
        'Andrew: 3 PRs open for Sales & Revenue (2 FE, 1 BE)',
        'Report-layer architecture decision (semantic layer vs. raw facts) still pending — Matt + Stephen reviewing test PR; go/no-go needed today',
        'Dagster PR #45 (void/discount/return metrics) needs to merge and warehouse must rebuild before demo data is complete',
        'Watch: demo script accuracy risks flagged — risk score described in script doesn\'t match what\'s built (3 booleans, not weighted ML); "upsell rate" definition incorrect vs. implementation; "AI-generated coaching insights" are rule-based templates, not AI. Needs correction before demo.',
        'Watch: report-layer architecture decision (semantic vs. raw facts) must be resolved today before pattern can be parallelized',
        'Watch: 10 open design questions on the sales & revenue module still pending architecture lock',
      ],
    },
    {
      name: 'Customer Sentiment',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-704',
      updatedAt: '2026-06-25T18:00:00',
      bullets: [
        'ARMA PR merged; Sarah polishing checkout survey UI for live demo tomorrow — Loom backup ready',
        'Matt: destructive DB migration PR and sentiment score work in progress',
        'Levi: enrichment data added and access query shared',
        'Replication PRs completing; Matt begins data modeling tomorrow',
        'Weedmaps: Eric following up with Chris around Monday — contingency plan confirmed (first-party surveys only if Weedmaps doesn\'t materialize)',
        'New paid feature: sentiment analysis confirmed as paid/gated — feature flag required (future flag + LD flag); confirm naming/scope with platform team',
        'Mobile responsiveness now on the radar',
        'Watch: Willian hit CI 401 error pulling @getdutchie/backoffice-ui-library from GitHub Package Registry — blocking PR merges',
        'Watch: permissions model (global vs. org-level) needs resolution — Marina coordinating with Casey and Willian',
        'Watch: follow-up email implementation (BeFree/marketing vs. SES/ARMA) needs alignment between John and Stacy',
        'Watch: July 20 alpha deadline being pressure-tested — Marina scheduling a full product walkthrough Monday to assess what\'s real vs. not. Significant timeline flag.',
      ],
    },
    {
      name: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      updatedAt: '2026-06-25T18:00:00',
      bullets: [
        'Acknowledge workflow scoped and in implementation: active → acknowledge (with who-acknowledged tracking) → dismiss',
        'Void frequency metric confirmed: transactions voided per hour/day count (not percentage) — aligned with Reporting team',
        'Phase 1 confirmed: dismiss-only; acting on alerts is Phase 2',
        'Demo tomorrow uses mock data aligned to prototypes — presenting aspirational UX, not current build state',
        'Loyalty fraud alerting stakeholder meeting today with loyalty and marketing',
        'Service vs. monolith decision still pending — current direction is monolith first; must resolve this week',
        'Watch: demo prototype stability unconfirmed — Ashley checking if prototype is locked for tonight/tomorrow',
        'Watch: org-level permissions architecture undefined for Signal Tower — Marina scheduling dedicated sync with Casey',
        'Watch: no global permissions implemented for Intelligence yet; global PIN concept exists but needs research',
        'Watch: compliance tab scope (Phase 1 vs Phase 2) still open — Marina reviewing with Katie',
        'Watch: alert freshness lag up to 2 hours from action to alert — stakeholders need to be aware',
        'Watch: service vs. monolith architecture decision must be resolved this week or migration effort doubles',
      ],
    },
    {
      name: 'Menu Boards',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-701',
      updatedAt: '2026-06-18T17:18:00',
      bullets: [
        'Chris Ostrowski remains technical DRI; Cyril Van Dyke joining for e-commerce engineering representation',
        "Proposed approach (pending Chris's approval): finish building the feature in e-commerce first, then start the work to move it into Nexus — potentially with the same resources",
        'First users may access it through e-commerce, but it ultimately lands in Nexus on or shortly after Phase 1',
      ],
    },
    {
      name: 'Voice AI',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-705',
      updatedAt: '2026-06-18T17:18:00',
      bullets: [
        'Chris Ostrowski remains technical DRI; Cyril Van Dyke joining for e-commerce engineering representation',
        "Proposed approach (pending Chris's approval): finish building the feature in e-commerce first, then start the work to move it into Nexus — potentially with the same resources",
        'First users may access it through e-commerce, but it ultimately lands in Nexus on or shortly after Phase 1',
      ],
    },
  ],

  driNotes: {
    title: 'DRI sync',
    updatedAt: '2026-06-25T18:00:00',
    decisions: [
      'July 20 alpha reality-check: Marina scheduling a full product walkthrough Monday to assess what\'s real vs. not — significant timeline pressure signal.',
      'Demo script accuracy (Reporting): risk score, upsell rate, and "AI coaching" descriptions in the demo script don\'t match what\'s actually built. Must be corrected before tomorrow\'s show-and-tell.',
      'Dex Day 1 scope swap proposed by Gordy: product copy across LSPs out, End-of-Day Reconciliation and Closing Reports in — based on C3 customer interviews. Leadership input needed.',
      'L4W vs. 30-day look-back: Connect switching to last-4-weeks — how much Nexus rework does this require? Needs fast triage.',
      'ADR-0005 proposed: capabilities auto-expose to Dex via client-side registry — needs Nexus FE + Dex/agent owner review.',
      'Sentiment analysis confirmed as a paid/gated feature — feature flag required; confirm naming/scope with platform team.',
      'QA engagement open: Ryan/Ben available for e2e, manual testing, and edge cases — teams should loop in early.',
    ],
    watch: [
      'July 20 alpha timeline: active pressure-test underway across Pulse, Sentiment, and other teams.',
      'Signal Tower service vs. monolith: must be resolved this week — delay doubles migration effort (2→4 weeks).',
      'Reporting demo script accuracy: several descriptions don\'t match actual implementation — needs correction before tomorrow.',
      'Inventory Snowflake → S3 → SQL Server: cross-team blocker, timeline and ownership still unclear.',
      'Willian (Customer Sentiment): CI 401 error blocking PR merges — @getdutchie/backoffice-ui-library pull failing.',
      'Inventory: Evan blocked by Snowflake RSA key not registered — needs Snowflake admin.',
      'Signal Tower demo tomorrow: presenting mock/prototype UX, not current build state.',
    ],
    actions: [
      'Gordy + leadership: decide on Dex Day 1 scope swap (product copy vs. EOD reconciliation + closing reports).',
      'Matt + Stephen: fast go/no-go on report-layer architecture (semantic layer vs. raw facts) — needed today.',
      'Reporting team: correct demo script accuracy issues before tomorrow\'s show-and-tell.',
      'Fix Willian\'s CI 401 error (GitHub Package Registry auth for @getdutchie/backoffice-ui-library).',
      'Snowflake admin: register Evan\'s RSA key in OPIJWHE-DEV for Inventory Planning.',
      'Gordy + Tara: triage L4W vs. 30-day look-back scope change with Connect team.',
      'Marina: schedule Monday product walkthrough to assess July 20 alpha readiness.',
      'Chris O.: Weedmaps CPO outreach — Eric following up ~Monday.',
    ],
  },

  // Phase 2 scope decisions — sourced from dutchie-nexus-prototype PRs.
  phase2Log: [
    {
      date: '2026-06-16',
      area: 'Platform',
      jiraUrl: 'https://dutchie.atlassian.net/browse/POS-17636',
      features: [
        'Hub SubTabBar (all secondary nav within hubs)',
        'All routes outside Phase 1 set: Orders, Products, Customers, Inventory hub, and all other hubs',
      ],
      decision: 'deferred',
      pr: 19,
      author: 'Roey Herzel',
      note: 'Framework PR establishing the Phase 1 nav config. Everything not listed in PHASE1_SIDEBAR / PHASE1_BOTTOM / PHASE1_MORE is Phase 2 by default.',
    },
    {
      date: '2026-06-17',
      area: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      features: [ 'Notes tab (Notes Intelligence)' ],
      decision: 'deferred',
      pr: 47,
      author: 'Roey Herzel',
    },
    {
      date: '2026-06-18',
      area: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      features: [
        '"Near-real-time / Real-time / Depends-on-sync" realism badges',
        '"SLA breached" badge',
        'SMS, Slack, and Push notification channels',
        'Investigate & Assign To actions',
      ],
      decision: 'deferred',
      pr: 60,
      author: 'Marina',
    },
    {
      date: '2026-06-18',
      area: 'Consumer Pulse',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-704',
      features: [
        'NPS tile', 'Unanswered tile', 'NPS Overview card',
        'Dex Insights card', 'Respond-to-reviews UI (PulseReviewCard)',
      ],
      decision: 'deferred',
      pr: 62,
      author: 'Marina',
    },
    {
      date: '2026-06-18',
      area: 'Budtender Performance',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      features: [
        'Market average row (MetricCard)', 'Risk calculation panel',
        'Insights recommendation', 'Coaching insights badge',
      ],
      decision: 'deferred',
      pr: 64,
      author: 'Marina',
      note: 'Risk score tile, signal alerts, loyalty flags, and incident timeline were later restored to Phase 1 via PR #66.',
    },
    {
      date: '2026-06-22',
      area: 'Budtender Performance',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      features: [
        'Risk score tile', 'Signal alerts', 'Loyalty flags', 'Incident timeline',
      ],
      decision: 'restored',
      pr: 66,
      author: 'Marina',
      note: 'Moved back to Phase 1 — originally deferred in PR #64.',
    },
  ],

  roster: [
    { project: 'Command Center',  dri: 'Amanda',    pm: 'Gordy',     fe: '',        be: '',                      de: ''             },
    { project: 'Signal Tower',    dri: 'Levi',      pm: 'Marina',    fe: 'Ashley',  be: 'Casey',                 de: 'Cossin / Levi' },
    { project: 'Consumer Pulse',  dri: 'Eric R',    pm: 'Marina',    fe: 'Willian', be: 'Sarah / Hunter / Willian', de: 'Cossin'    },
    { project: 'Inventory',       dri: 'Ned',       pm: 'Gordy',     fe: 'Evan M',  be: 'Rex / Roey / Steven Morton', de: 'Cossin' },
    { project: 'Reports',         dri: 'Amanda',    pm: 'Marina',    fe: 'Mack',    be: 'Gardner / Seth / Luon', de: 'Cossin'       },
    { project: 'Menu Boards',     dri: 'Chris Ostrowski',            ecom: 'Cyril Van Dyke' },
    { project: 'Voice AI',        dri: 'Chris Ostrowski',            ecom: 'Cyril Van Dyke' },
    { project: 'Dex',             dri: 'Crispy',    pm: 'Gordy',     fe: 'Scott',   be: 'Driban',                de: 'Crispy'       },
    { project: 'Wayfinder',       dri: 'Livergood', pm: 'Livergood', fe: 'Roey',    be: 'Livergood / Roey',      de: 'Livergood'    },
  ],
};
