/*
 * Nexus Daily Summary — data source of truth.
 */
window.NEXUS_DATA = {
  launchDate: '2026-07-20',
  launchLabel: '7/20',
  date: '2026-06-24',

  teams: [
    {
      name: 'Inventory Planning',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-700',
      updatedAt: '2026-06-24T18:00:00',
      bullets: [
        'All three green milestones on target — SKU View/Table, SKU Table UI (with mock API), and back-end contracts all progressing',
        'Rex: WIP LeafLogix draft PR for SKU table posted — data contract needs team review before merging',
        'Evan: live SKU table prototype shared with placeholder data',
        'Reporting model PR merged adding missing columns (sell_through_rate approximation); fast-follow correction PR submitted',
        'Stephen: PR merged making detail available; next step is S3 export linked to SQL Server',
        'Ned onboarding; Roey on vacation (returns July 6 — BE refinement starts then); Mike rotated off',
        'Watch: data contract in Rex\'s WIP SKU table PR needs team review before committing',
        'Watch: Data DRI ownership has shifted and needs formal clarification',
        'Watch: New Purchase Order system (Whit Perkins) — Nexus ops that populate POs require Inventory UI to close the loop',
        'Mitigation: contracts + expected data state agreed to continue work despite blocker; focused discussion scheduled on timeline + ownership',
        'Blocked: Snowflake → S3 → SQL Server pipeline not yet done — blocking final delivery. Cross-team concern escalated to Eric Livergood, Chris Ostrowski, and Tom Wonneberger',
      ],
    },
    {
      name: 'Dex',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-707',
      updatedAt: '2026-06-24T18:00:00',
      bullets: [
        'Phase 1 scope locked at 5 use cases; workflows in active implementation',
        'Scott Dietrich: focused on AI Budtender (Register Gamification); standup was async today due to Chris\'s schedule conflict — limited visibility into today\'s progress',
        'Campbell: unit tests for Dex submitted; capabilities layer + campaign flow work ongoing',
        'Chris to post proposal for a shared API surface for FE UI components and Dex (ADR-0005 proposed — needs Dex/agent owner review and sign-off)',
        'Katie Goodwin: brainstorming Day 2+ use cases with Bilda + Contexta; mapping triggers, invocation type, context, and access needs into a consumable doc',
        'Driban out ~2 weeks on paternity leave; dropped 2 draft PRs before departing — scope held for his return',
        'Product decisions: Phase 1 invocation uses two existing pathways only (inline deferred to P2); free text allowed as build signal; auditing lean toward a "done by Dex" flag + person in conversation',
        'Watch: Dex flagged as a potential risk — Scott\'s bandwidth reduced while on AI Budtender; Chris is sole driver for now',
        'Watch: no performed-by field in the current audit flow — audit UX clunky; Chris investigating',
      ],
    },
    {
      name: 'Command Center',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-703',
      updatedAt: '2026-06-23T16:48:00',
      paused: true,
      pausedReason: 'On hold — roll-up sections resume with Reporting; two standalone sections (Today\'s Pulse + one Morning Brief item) need separate planning.',
      bullets: [
        'DRI recommendation: piggyback roll-up sections off Reporting work; plan Today\'s Pulse and one Morning Brief item separately as standalone sections',
        'Gordy auditing Command Center to identify all non-roll-up sections and produce a list for planning',
        'Today\'s Pulse and one Morning Brief item confirmed as standalone — not covered by Reporting work; require separate work to determine data sources',
        'Resource shuffle: Mike Luon → Reports; Steven Morton → Inventory Insights; Rex → Inventory Planning (back-end)',
        'Scott on Register Copilot',
        'No channel activity today — milestone canvas for week of 6/22 not yet filled in',
      ],
    },
    {
      name: 'Reporting',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      updatedAt: '2026-06-24T18:00:00',
      bullets: [
        'Strong progress toward Friday show-and-tell — budtender performance detail page PR submitted; refinement doc merged with architecture decisions',
        'Storybook now wired up in VAPE for pre-endpoint rendering',
        'Sales & revenue refinement doc posted with 10 open design questions — must be resolved to lock architecture',
        'Bug fix PR submitted on order item fact',
        'Andrew on-site at a dispensary today (Upstate Elevator, Vermont) — async but good field engagement signal',
        'Watch: Seth\'s Snowflake RSA key missing locally — blocked on dev work until resolved',
        'Watch: 10 open design questions on the sales & revenue module must be closed before architecture can be locked',
        'Watch: report-layer architecture decision (semantic layer vs. raw facts) — Matt + Stephen need a fast go/no-go before pattern can be parallelized',
      ],
    },
    {
      name: 'Customer Sentiment',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-704',
      updatedAt: '2026-06-24T18:00:00',
      bullets: [
        'GoldDB sample data now fully available in all environments; replication PRs completing today — Matt begins data modeling tomorrow',
        'Willian: Locations tab PRs reviewed and approved',
        'ARMA PR ready for review and testing — Sarah targeting morning release tomorrow, then shifting to front-end prototype work',
        'Marina: prototype cleanup in progress (brands, pain points, chip layout, permissioning); Amanda potentially taking on briefs work (raw data + AI queries)',
        'Weedmaps: Chris O. sent note to Weedmaps CPO (no response yet); Eric pulling real data on develop for a couple of customers',
        'New: sentiment analysis confirmed as a paid/gated feature — Willian to implement feature flagging (future flag + LD flag); confirm flag naming/scope with platform team',
        'Mobile responsiveness of the UI now on the radar',
        'Watch: source type filtering flagged by Eric as a backend impact item — needs investigation',
        'Watch: auth issues testing PAPI endpoint; Rspec workaround required for CI on VAPE',
        'Watch: unresolved — should survey display for ecomm dispensaries without a LeafLogix integration?',
        'Watch: John\'s prototype designs pushed to next week (stretched across multiple AI projects) — design capacity concern',
      ],
    },
    {
      name: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      updatedAt: '2026-06-24T18:00:00',
      bullets: [
        'Alerts UI PR submitted to align front-end schema with back-end',
        'Casey continuing on alert settings and threshold configs',
        'Phase 1 confirmed: ships with dismiss-only; "resolve" action is Phase 2',
        'Email notifications confirmed for Phase 1; Marina updating prototypes with email samples',
        'Demo data problem addressed: Mike Luan looped in for refreshable external-facing Snowflake demo data',
        'Loyalty fraud alerting stakeholder meeting tomorrow (loyalty + marketing)',
        'Service vs. monolith decision being finalized this week — current direction is monolith first, build service in parallel; Casey flagged post-launch migration doubles timeline (2→4 weeks)',
        'Watch: email alert designs/branding — no designs exist yet; needs attention',
        'Watch: compliance tab scope (Phase 1 vs Phase 2) still open — Marina reviewing with Katie',
        'Watch: permissioning for Signal Tower undefined — Marina defining and documenting to unblock Casey',
        'Watch: alert freshness lag up to 2 hours from action to alert (1hr evaluation + 1hr Snowflake) — stakeholders need to be aware',
        'Watch: service vs. monolith architecture decision must be resolved this week or migration effort doubles',
      ],
    },
    {
      name: 'Menu Boards',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-701',
      updatedAt: '2026-06-18T17:18:00',
      bullets: [
        'Chris Ostrowski remains technical DRI; Cyril Van Dyke joining for e-commerce engineering representation',
        "Proposed approach (pending Chris's approval): finish building the feature in e-commerce first, then start the work to move it into Nexus — potentially with the same resources",
        'First users may access it through e-commerce, but it ultimately lands in Nexus on or shortly after Phase 1',
      ],
    },
    {
      name: 'Voice AI',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-705',
      updatedAt: '2026-06-18T17:18:00',
      bullets: [
        'Chris Ostrowski remains technical DRI; Cyril Van Dyke joining for e-commerce engineering representation',
        "Proposed approach (pending Chris's approval): finish building the feature in e-commerce first, then start the work to move it into Nexus — potentially with the same resources",
        'First users may access it through e-commerce, but it ultimately lands in Nexus on or shortly after Phase 1',
      ],
    },
  ],

  driNotes: {
    title: 'DRI sync',
    updatedAt: '2026-06-24T18:00:00',
    decisions: [
      'ADR-0005 proposed: capabilities auto-expose to Dex via client-side registry — needs review and sign-off from Nexus FE + Dex/agent owners.',
      'Sentiment analysis confirmed as a paid/gated feature — feature flag required (future flag + LD flag). Willian implementing; confirm naming/scope with platform team.',
      'Signal Tower Phase 1: ships with dismiss-only; "resolve" action is Phase 2.',
      'QA engagement opened: Ryan/Ben (QA) formally available for e2e exploration, edge cases, and manual testing — teams encouraged to loop in early for code-complete features.',
      'Command Center: roll-up sections piggyback off Reporting; Today\'s Pulse + one Morning Brief item are standalone and need separate planning. Gordy auditing.',
      'Friday show-and-tell at 1:30 PM ET — Budtender Reporting is the lead demo; teams demo from develop.backoffice.dutchie.dev.',
    ],
    watch: [
      'Signal Tower service vs. monolith: must be resolved this week — Casey flagged delay doubles migration effort (2→4 weeks).',
      'Inventory Snowflake → S3 → SQL Server: cross-team blocker with unclear ownership; focused discussion scheduled.',
      'Reporting: 10 open design questions on the sales & revenue module blocking architecture lock.',
      'Reporting: Seth\'s Snowflake RSA key missing locally — blocked on dev work.',
      'Ben (QA): LLx Dev Login credentials not working — blocks QA engagement on dev environment.',
      'Chart library decision pending: Recharts vs. shadcn/ui charts for detail pages.',
      'Consumer Pulse: unresolved — should survey display for ecomm dispensaries without LeafLogix integration?',
    ],
    actions: [
      'Matt + Stephen: fast go/no-go on report-layer architecture (semantic layer vs. raw facts/dimensions).',
      'Andrew + team: resolve 10 open design questions in sales & revenue refinement doc.',
      'Platform team: confirm feature flag naming/scope for sentiment analysis (paid feature).',
      'All teams: loop in Ryan/Ben (QA) proactively for e2e + manual testing on code-complete work.',
      'Gordy: audit Command Center for non-roll-up sections; plan standalone sections (Today\'s Pulse, Morning Brief).',
      'Eric: stand up Pathfinder; create API surface for Roey (avoid GraphQL reliance or confirm constraints).',
      'Chris O.: Weedmaps CPO outreach — awaiting response on data access partnership.',
    ],
  },

  // Phase 2 scope decisions — sourced from dutchie-nexus-prototype PRs.
  // Each entry: date (Eastern), area, features[], decision ('deferred'|'restored'), pr #, author, optional note.
  phase2Log: [
    {
      date: '2026-06-16',
      area: 'Platform',
      jiraUrl: 'https://dutchie.atlassian.net/browse/POS-17636',
      features: [
        'Hub SubTabBar (all secondary nav within hubs)',
        'All routes outside Phase 1 set: Orders, Products, Customers, Inventory hub, and all other hubs',
      ],
      decision: 'deferred',
      pr: 19,
      author: 'Roey Herzel',
      note: 'Framework PR establishing the Phase 1 nav config. Everything not listed in PHASE1_SIDEBAR / PHASE1_BOTTOM / PHASE1_MORE is Phase 2 by default.',
    },
    {
      date: '2026-06-17',
      area: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      features: [
        'Notes tab (Notes Intelligence)',
      ],
      decision: 'deferred',
      pr: 47,
      author: 'Roey Herzel',
    },
    {
      date: '2026-06-18',
      area: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      features: [
        '"Near-real-time / Real-time / Depends-on-sync" realism badges',
        '"SLA breached" badge',
        'SMS, Slack, and Push notification channels',
        'Investigate & Assign To actions',
      ],
      decision: 'deferred',
      pr: 60,
      author: 'Marina',
    },
    {
      date: '2026-06-18',
      area: 'Consumer Pulse',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-704',
      features: [
        'NPS tile',
        'Unanswered tile',
        'NPS Overview card',
        'Dex Insights card',
        'Respond-to-reviews UI (PulseReviewCard)',
      ],
      decision: 'deferred',
      pr: 62,
      author: 'Marina',
    },
    {
      date: '2026-06-18',
      area: 'Budtender Performance',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      features: [
        'Market average row (MetricCard)',
        'Risk calculation panel',
        'Insights recommendation',
        'Coaching insights badge',
      ],
      decision: 'deferred',
      pr: 64,
      author: 'Marina',
      note: 'Risk score tile, signal alerts, loyalty flags, and incident timeline were later restored to Phase 1 via PR #66.',
    },
    {
      date: '2026-06-22',
      area: 'Budtender Performance',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      features: [
        'Risk score tile',
        'Signal alerts',
        'Loyalty flags',
        'Incident timeline',
      ],
      decision: 'restored',
      pr: 66,
      author: 'Marina',
      note: 'Moved back to Phase 1 — originally deferred in PR #64.',
    },
  ],

  roster: [
    { project: 'Command Center',  dri: 'Amanda',    pm: 'Gordy',     fe: '',        be: '',                      de: ''             },
    { project: 'Signal Tower',    dri: 'Levi',      pm: 'Marina',    fe: 'Ashley',  be: 'Casey',                 de: 'Cossin / Levi' },
    { project: 'Consumer Pulse',  dri: 'Eric R',    pm: 'Marina',    fe: 'Willian', be: 'Sarah / Hunter / Willian', de: 'Cossin'    },
    { project: 'Inventory',       dri: 'Ned',       pm: 'Gordy',     fe: 'Evan M',  be: 'Rex / Roey / Steven Morton', de: 'Cossin' },
    { project: 'Reports',         dri: 'Amanda',    pm: 'Marina',    fe: 'Mack',    be: 'Gardner / Seth / Luon', de: 'Cossin'       },
    { project: 'Menu Boards',     dri: 'Chris Ostrowski',            ecom: 'Cyril Van Dyke' },
    { project: 'Voice AI',        dri: 'Chris Ostrowski',            ecom: 'Cyril Van Dyke' },
    { project: 'Dex',             dri: 'Crispy',    pm: 'Gordy',     fe: 'Scott',   be: 'Driban',                de: 'Crispy'       },
    { project: 'Wayfinder',       dri: 'Livergood', pm: 'Livergood', fe: 'Roey',    be: 'Livergood / Roey',      de: 'Livergood'    },
  ],
};
