/*
 * Nexus Daily Summary — data source of truth.
 */
window.NEXUS_DATA = {
  launchDate: '2026-07-20',
  launchLabel: '7/20',
  date: '2026-06-23',

  teams: [
    {
      name: 'Inventory Planning',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-700',
      updatedAt: '2026-06-23T15:58:00',
      bullets: [
        'SKU Table/View, SKU Table UI (with mock API), and back-end contracts all progressing; three milestones on track',
        'Stephen: PR merged making detail available; next step is S3 export linked to SQL Server',
        'Evan: WIP prototype of SKU table in progress; building base components for Nexus consistency, continuing to pick away at other prototype components',
        'Rex: Nexus crash-course complete, constellation set up in VAPE; refining back-end contracts with Stephen and Evan',
        'Gordy: small UI tweaks (de-nesting double-nested columns)',
        'Ned onboarding; Roey on vacation (returns July 6 — BE refinement work starts then); Mike rotating off team',
        'Watch: Data DRI ownership has shifted and needs formal clarification',
        'Watch: New Purchase Order system flagged by Whit Perkins — Nexus operations that add to order will populate POs, and the UI needs to close the loop',
        'Mitigation: team will agree on contracts + expected data state to continue SKU table work even while the blocker is unresolved; focused discussion to be scheduled on timeline and ownership',
        'Blocked: Snowflake → S3 → SQL Server pipeline not yet done — blocking final delivery. A global concern escalated to Eric Livergood, Chris Ostrowski, and Tom Wonneberger',
      ],
    },
    {
      name: 'Dex',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-707',
      updatedAt: '2026-06-23T12:19:00',
      bullets: [
        'Phase 1 scope locked at 5 use cases; workflows in active implementation',
        'Scott Dietrich: focused on AI Budtender (Register Gamification) — reduced bandwidth for Dex; Chris Campbell is currently the primary Dex driver. Flagged as a potential risk.',
        'Campbell: drafted capabilities layer for Nexus (per Chris request); back to campaign flow — allowing campaigns to start from a template; reviewed and approved Dreeben\'s draft PRs from before paternity leave',
        'Chris to post proposal for a shared API surface for FE UI components and Dex — enabling non-Dex teams to build Dex-consumable features',
        'Katie Goodwin: brainstorming Day 2+ Dex use cases for Products & Inventory with Bilda + Contexta; mapping out triggers, invocation type, context Dex inherits, and access needs into a consumable doc — brief refinements to follow',
        'Driban out ~2 weeks on paternity leave; dropped 2 draft PRs before departing — scope held for his return',
        'Product decisions: Phase 1 invocation uses two existing pathways only (inline deferred to P2); free text allowed as build signal; auditing lean toward a "done by Dex" flag + person in conversation',
        'Non-Dex build pattern: Campbell accepted establishing a standard for non-Dex teams to build Dex-consumable features (data/action/presentation layers)',
        'Watch: Dex flagged as a potential risk — Scott\'s bandwidth reduced while on AI Budtender; Chris is sole driver for now',
        'Watch: no performed-by field in the current audit flow — audit UX clunky; Chris investigating',
      ],
    },
    {
      name: 'Command Center',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-703',
      updatedAt: '2026-06-23T16:48:00',
      paused: true,
      pausedReason: 'On hold — roll-up sections resume with Reporting; two standalone sections (Today\'s Pulse + one Morning Brief item) need separate planning.',
      bullets: [
        'DRI recommendation: piggyback roll-up sections off Reporting work; plan Today\'s Pulse and one Morning Brief item separately as standalone sections',
        'Gordy auditing Command Center to identify all non-roll-up sections and produce a list for planning',
        'Today\'s Pulse and one Morning Brief item confirmed as standalone — not covered by Reporting work; require separate work to determine data sources',
        'Resource shuffle: Mike Luon → Reports; Steven Morton → Inventory Insights; Rex → Inventory Planning (back-end)',
        'Scott on Register Copilot',
      ],
    },
    {
      name: 'Reporting',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      updatedAt: '2026-06-23T15:55:00',
      bullets: [
        'Budtender performance report end-to-end demo for Friday\'s show-and-tell; serves as the reusable framework — remaining report pages copy the pattern and build in parallel once it lands',
        'Mack: refinement doc merged with architecture decisions; Budtender performance page spun up, addressing Evan\'s PR feedback (merge soon); next: individual budtender page view',
        'Seth: PR out shortly for semantic view + data model changes to capture missing budtender metrics; leaflogix controller endpoints started — targeting finish today/tomorrow',
        'Matt + Stephen: scoping a small report-layer change so reports read metric definitions from the semantic layer (not raw facts and dimensions); Stephen testing against a live report for a quick go/no-go',
        'Andrew: refinement doc posted for the sales & revenue module; addressing open design decisions before locking the architectural section and chunking out the work',
        'Marina: design review and updates complete across all reports; assessing morning brief feasibility, then provisioning and config checks',
        'Command Center reporting dependencies flagged — parking-lot conversation needed with Gordy and Tara to clarify what Reporting work unblocks vs. what Command Center needs separately',
        'Brands report design review still pending — scheduled with Whit Perkins',
        'Open question: should selectable date ranges be constrained (e.g., past 1 year only) to avoid performance issues from legacy reporting?',
        'Watch: report-layer architecture decision pending (Matt + Stephen) — resolving fast to lock consistent patterns before parallelizing',
      ],
    },
    {
      name: 'Customer Sentiment',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-704',
      updatedAt: '2026-06-23T16:44:00',
      bullets: [
        'Replication PRs completing today — data starts flowing to all environments; Matt begins modeling tomorrow and meeting with Levi on themes/tagging pipeline',
        'ARMA PR ready for review and testing — Sarah targeting morning release, then shifting to front-end prototype work; sharing data flow diagram with team',
        'Willian: controllers + repositories in place with mocked data; all FE connected (Eric approved both PRs)',
        'John\'s updated prototype designs pushed to next week (stretched across multiple AI projects); Sarah confirmed she can work with existing designs in the meantime',
        'Marina: prototype cleanup in progress — refining brands, pain points, and chip layout, incorporating permissioning',
        'Amanda potentially taking on briefs work (raw data + AI queries)',
        'Weedmaps: Chris O. sent note to Weedmaps CPO (no response yet); Eric already pulling real data on develop for a couple of customers',
        'Watch: source type filtering flagged by Eric as a backend impact item — needs investigation',
        'Watch: auth issues testing PAPI endpoint; Rspec workaround required to run CI on VAPE',
        'Watch: unresolved — should survey display for ecomm dispensaries without a LeafLogix integration, and where does that data get stored?',
      ],
    },
    {
      name: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      updatedAt: '2026-06-23T16:40:00',
      bullets: [
        'Service vs. monolith decision being finalized this week — current direction is monolith first, build service in parallel; Casey flagged post-launch migration doubles the timeline (2→4 weeks)',
        'Email notifications confirmed for Phase 1; Marina updating prototypes with email samples',
        'Permissioning for Signal Tower undefined — Marina defining and documenting today to unblock Casey on threshold and alert configs',
        'Matt Cossin: walking through discount/metric business logic with Silverblatt today; moving to void rate queries after — goal: business logic reviewed and queried by EOD',
        'Ashley Long: consolidated FE PR out for review; syncing with Mack on budtender performance page and risk score breakdown',
        'Demo data problem addressed: Mike Luan looped in to create refreshable external-facing demo data in Snowflake',
        'Loyalty fraud alerting meeting tomorrow with loyalty and marketing stakeholders',
        'Watch: compliance tab scope (Phase 1 vs Phase 2) still open — Marina reviewing with Katie',
        'Watch: alert freshness lag up to 2 hours from action to alert (1hr evaluation + 1hr Snowflake) — stakeholders need to be aware',
        'Watch: service vs. monolith architecture — decision targeted for this week; resolution needed before build continues at scale',
      ],
    },
    {
      name: 'Menu Boards',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-701',
      updatedAt: '2026-06-18T17:18:00',
      bullets: [
        'Chris Ostrowski remains technical DRI; Cyril Van Dyke joining for e-commerce engineering representation',
        "Proposed approach (pending Chris's approval): finish building the feature in e-commerce first, then start the work to move it into Nexus — potentially with the same resources",
        'First users may access it through e-commerce, but it ultimately lands in Nexus on or shortly after Phase 1',
      ],
    },
    {
      name: 'Voice AI',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-705',
      updatedAt: '2026-06-18T17:18:00',
      bullets: [
        'Chris Ostrowski remains technical DRI; Cyril Van Dyke joining for e-commerce engineering representation',
        "Proposed approach (pending Chris's approval): finish building the feature in e-commerce first, then start the work to move it into Nexus — potentially with the same resources",
        'First users may access it through e-commerce, but it ultimately lands in Nexus on or shortly after Phase 1',
      ],
    },
  ],

  driNotes: {
    title: 'DRI sync',
    updatedAt: '2026-06-23T16:48:00',
    decisions: [
      'Command Center: roll-up sections piggyback off Reporting; Today\'s Pulse and one Morning Brief item are standalone and need separate planning. Gordy auditing to identify all non-roll-up sections.',
      'Inventory reverse ETL mitigation: team to agree on contracts + expected data state to continue SKU table work despite the S3→SQL Server blocker; focused discussion to be scheduled.',
      'Pathfinder: Eric standing up Pathfinder for the team; main task is creating an API surface so Roey can continue work without GraphQL reliance when he returns.',
      'Shared API surface proposal: Chris Campbell preparing a proposal for a shared API surface for FE UI components and Dex — post coming soon.',
      'QA resourcing resolved: Ben (primary) + cnochez (backup). Ben on parental leave end of July; will coordinate with QIE for testing-infra needs.',
      'Friday show-and-tell at 1:30 PM ET from develop.backoffice.dutchie.dev — Budtender Reporting is the lead demo.',
    ],
    watch: [
      'Dex at potential risk: Scott focused on AI Budtender reducing Dex bandwidth; Chris Campbell is sole driver. Team generally ahead except for this.',
      'Inventory reverse ETL blocker (S3 → SQL Server): timeline and ownership still being determined — focused discussion needed.',
      'Signal Tower service vs. monolith: direction is monolith first with parallel service build; decision being finalized this week.',
      'Consumer Pulse: unresolved question — should survey display for ecomm dispensaries without LeafLogix integration, and where does data go?',
      'Signal Tower + Reporting alignment: must coordinate on shared budtender performance/risk modal to avoid duplication.',
    ],
    actions: [
      'Gordy: audit Command Center to list non-roll-up sections; plan how to obtain required data for standalone sections (Today\'s Pulse, Morning Brief item).',
      'Eric: stand up Pathfinder; create API surface for Roey to avoid GraphQL reliance (or confirm why GraphQL must remain).',
      'Chris Campbell: post shared API surface proposal for FE + Dex.',
      'Schedule focused discussion on reverse ETL blocker: how long will it take and who owns it?',
      'Chris O.: Weedmaps CPO outreach — awaiting response on data access partnership.',
      'Levi: Connect with Sam Petrowski (ACH Ops) on fraud signal list + costs.',
    ],
  },

  // Phase 2 scope decisions — sourced from dutchie-nexus-prototype PRs.
  // Each entry: date (Eastern), area, features[], decision ('deferred'|'restored'), pr #, author, optional note.
  phase2Log: [
    {
      date: '2026-06-16',
      area: 'Platform',
      jiraUrl: 'https://dutchie.atlassian.net/browse/POS-17636',
      features: [
        'Hub SubTabBar (all secondary nav within hubs)',
        'All routes outside Phase 1 set: Orders, Products, Customers, Inventory hub, and all other hubs',
      ],
      decision: 'deferred',
      pr: 19,
      author: 'Roey Herzel',
      note: 'Framework PR establishing the Phase 1 nav config. Everything not listed in PHASE1_SIDEBAR / PHASE1_BOTTOM / PHASE1_MORE is Phase 2 by default.',
    },
    {
      date: '2026-06-17',
      area: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      features: [
        'Notes tab (Notes Intelligence)',
      ],
      decision: 'deferred',
      pr: 47,
      author: 'Roey Herzel',
    },
    {
      date: '2026-06-18',
      area: 'Signal Tower',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-702',
      features: [
        '"Near-real-time / Real-time / Depends-on-sync" realism badges',
        '"SLA breached" badge',
        'SMS, Slack, and Push notification channels',
        'Investigate & Assign To actions',
      ],
      decision: 'deferred',
      pr: 60,
      author: 'Marina',
    },
    {
      date: '2026-06-18',
      area: 'Consumer Pulse',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-704',
      features: [
        'NPS tile',
        'Unanswered tile',
        'NPS Overview card',
        'Dex Insights card',
        'Respond-to-reviews UI (PulseReviewCard)',
      ],
      decision: 'deferred',
      pr: 62,
      author: 'Marina',
    },
    {
      date: '2026-06-18',
      area: 'Budtender Performance',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      features: [
        'Market average row (MetricCard)',
        'Risk calculation panel',
        'Insights recommendation',
        'Coaching insights badge',
      ],
      decision: 'deferred',
      pr: 64,
      author: 'Marina',
      note: 'Risk score tile, signal alerts, loyalty flags, and incident timeline were later restored to Phase 1 via PR #66.',
    },
    {
      date: '2026-06-22',
      area: 'Budtender Performance',
      jiraUrl: 'https://dutchie.atlassian.net/browse/ROAD-706',
      features: [
        'Risk score tile',
        'Signal alerts',
        'Loyalty flags',
        'Incident timeline',
      ],
      decision: 'restored',
      pr: 66,
      author: 'Marina',
      note: 'Moved back to Phase 1 — originally deferred in PR #64.',
    },
  ],

  roster: [
    { project: 'Command Center',  dri: 'Amanda',    pm: 'Gordy',     fe: '',        be: '',                      de: ''             },
    { project: 'Signal Tower',    dri: 'Levi',      pm: 'Marina',    fe: 'Ashley',  be: 'Casey',                 de: 'Cossin / Levi' },
    { project: 'Consumer Pulse',  dri: 'Eric R',    pm: 'Marina',    fe: 'Willian', be: 'Sarah / Hunter / Willian', de: 'Cossin'    },
    { project: 'Inventory',       dri: 'Ned',       pm: 'Gordy',     fe: 'Evan M',  be: 'Rex / Roey / Steven Morton', de: 'Cossin' },
    { project: 'Reports',         dri: 'Amanda',    pm: 'Marina',    fe: 'Mack',    be: 'Gardner / Seth / Luon', de: 'Cossin'       },
    { project: 'Menu Boards',     dri: 'Chris Ostrowski',            ecom: 'Cyril Van Dyke' },
    { project: 'Voice AI',        dri: 'Chris Ostrowski',            ecom: 'Cyril Van Dyke' },
    { project: 'Dex',             dri: 'Crispy',    pm: 'Gordy',     fe: 'Scott',   be: 'Driban',                de: 'Crispy'       },
    { project: 'Wayfinder',       dri: 'Livergood', pm: 'Livergood', fe: 'Roey',    be: 'Livergood / Roey',      de: 'Livergood'    },
  ],
};
